In [1]:
%matplotlib inline
import numpy as np
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

#資料集載入的內容&資料集&目標集
iris=load_iris()
X = iris.data
Y = iris.target

##noisy
target_dims = iris.data.shape
noise = np.random.randn(target_dims[0],target_dims[1])

##資料做伸縮加noisy
multi =[np.random.randint(1,10),np.random.randint(1,10),np.random.randint(1,10),np.random.randint(1,10)]
multi = np.diag(multi)
#print("multi\n",multi)
X1 = X.transpose()
multi_target = multi.dot(X1).transpose()
#print("multi_target\n",multi_target)
noisy_target = multi_target + noise
#print("noisy_target\n",noisy_target)

#將資料分為測試&訓練兩類，並將測試集設為25%
x_train, x_test,y_train, y_test = train_test_split(noisy_target,Y,test_size=0.25,random_state=0)

#利用SVM帶入資料做訓練
clf= svm.SVC(gamma='auto')
clf.fit(x_train, y_train)

#測試的準確度
Accuracy=clf.score(x_test, y_test)
print("測試Accuracy",Accuracy)

#將測試資料帶入做預測
y_predict = clf.predict(x_test)
target_names=['Setosa','Versicolour','Virginica']
print ("混淆矩陣",'\n',metrics.confusion_matrix(y_test,y_predict))
print ("預測Accuracy",metrics.accuracy_score(y_test,y_predict))
print(metrics.classification_report(y_test,y_predict,target_names=target_names))

#畫出roc計算AUC
fpr, tpr, thresholds = metrics.roc_curve(y_test, y_predict, pos_label=2)
print("AUC:",metrics.auc(fpr, tpr))


測試Accuracy 0.9736842105263158
混淆矩陣 
 [[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]
預測Accuracy 0.9736842105263158
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        13
 Versicolour       0.94      1.00      0.97        16
   Virginica       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

AUC: 0.9693486590038314
