In [2]:
%matplotlib inline
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import *

#資料集載入的內容&資料集&目標集
iris=load_iris()
X = iris.data
Y = iris.target
#print(iris.DESCR)

#將資料分為測試&訓練兩類，並將測試集設為25%
x_train, x_test,y_train, y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

#利用SVM帶入資料做訓練
clf= SVC(gamma='auto')
clf.fit(x_train, y_train)

#測試的準確度
Accuracy=clf.score(x_test, y_test)
print("測試Accuracy",Accuracy)

#將測試資料帶入做預測
y_predict = clf.predict(x_test)
target_names=['Setosa','Versicolour','Virginica']
print ("混淆矩陣",'\n',confusion_matrix(y_test,y_predict))
print ("預測Accuracy",accuracy_score(y_test,y_predict))
print(classification_report(y_test,y_predict,target_names=target_names))


import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
#畫出roc計算AUC
fpr, tpr, thresholds = roc_curve(y_test, y_predict, pos_label=2)
print("AUC:",auc(fpr, tpr))


測試Accuracy 0.9736842105263158
混淆矩陣 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
預測Accuracy 0.9736842105263158
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        13
 Versicolour       1.00      0.94      0.97        16
   Virginica       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

AUC: 0.9827586206896552
